version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Map port 3000 inside the container to port 80 on the host
    environment:
      - NODE_ENV=production
# Removed volumes for production to ensure the container is immutable
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules