version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: host/dev
      args:
        - DOMAIN_NAME=local.${DOMAIN_NAME}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - web
